In [1]:
import pandas as pd

In [38]:
df = pd.read_csv("questions_draft.txt" )

In [39]:
df

    question
0       velo
1       auto
2        pot
3       pipi
4       caca
..       ...
151   classe
152     clou
153      sac
154      lac
155     avec

[156 rows x 1 columns]

In [40]:
df['key']=df.index+27

In [41]:
df

    question  key
0       velo   27
1       auto   28
2        pot   29
3       pipi   30
4       caca   31
..       ...  ...
151   classe  178
152     clou  179
153      sac  180
154      lac  181
155     avec  182

[156 rows x 2 columns]

In [42]:
df['key']="q_"+df.key.astype(str)
dico = df.to_dict('records')

In [52]:
lista=[d['key']+" : " +d['question'] for d in dico]

In [54]:
for i in lista:
    print(i)

q_27 : velo
q_28 : auto
q_29 : pot
q_30 : pipi
q_31 : caca
q_32 : bobo
q_33 : lasso
q_34 : beau
q_35 : bouton
q_36 : ami
q_37 : papa
q_38 : avec
q_39 : maman
q_40 : va
q_41 : chat
q_42 : regarde
q_43 : moto
q_44 : stylo
q_45 : montre
q_46 : qui
q_47 : tortue
q_48 : petit
q_49 : jardin
q_50 : ecole
q_51 : lire
q_52 : livre
q_53 : histoire
q_54 : lune
q_55 : lilas
q_56 : salut
q_57 : repas
q_58 : chaud
q_59 : maison
q_60 : rouge
q_61 : demain
q_62 : telephone
q_63 : mal
q_64 : tete
q_65 : midi
q_66 : samedi
q_67 : rame
q_68 : tomate
q_69 : mardi
q_70 : tarte
q_71 : petit
q_72 : matelas
q_73 : radis
q_74 : larme
q_75 : rue
q_76 : nuit
q_77 : non
q_78 : noir
q_79 : jupe
q_80 : puma
q_81 : puce
q_82 : pull
q_83 : autruche
q_84 : hippopotame
q_85 : chameau
q_86 : animal
q_87 : tulipe
q_88 : note
q_89 : pomme
q_90 : promenade
q_91 : tissu
q_92 : sirop
q_93 : dessine
q_94 : aussi
q_95 : ici
q_96 : racine
q_97 : sonne
q_98 : saute
q_99 : saucisse
q_100 : seau
q_101 : limace
q_102 : police
q_103 : place
q_104 : loup
q_105 : lourd
q_106 : roue
q_107 : mousse
q_108 : moule
q_109 : semoule
q_110 : nous
q_111 : souris
q_112 : soupe
q_113 : sourire
q_114 : souple
q_115 : source
q_116 : toupie
q_117 : pouce
q_118 : poule
q_119 : renard
q_120 : tarte
q_121 : marteau
q_122 : partir
q_123 : sortir
q_124 : courir
q_125 : tenir
q_126 : salir
q_127 : cirque
q_128 : porte
q_129 : parasol
q_130 : pourquoi
q_131 : purée
q_132 : cinéma
q_133 : année
q_134 : poupée
q_135 : date
q_136 : rideau
q_137 : malade
q_138 : stupide
q_139 : rapide
q_140 : poudre
q_141 : drapeau
q_142 : drôle
q_143 : masque
q_144 : poste
q_145 : costume
q_146 : triste
q_147 : laine
q_148 : laisse
q_149 : semaine
q_150 : dromadaire
q_151 : merci
q_152 : perle
q_153 : dessert
q_154 : terre
q_155 : tonnerre
q_156 : respire
q_157 : omelette
q_158 : allumette
q_159 : sucette
q_160 : sonnette
q_161 : lettre
q_162 : sel
q_163 : tunnel
q_164 : pelle
q_165 : cadeau
q_166 : canard
q_167 : culotte
q_168 : calcul
q_169 : kilo
q_170 : kimono
q_171 : couteau
q_172 : casque
q_173 : perroquet
q_174 : ticket
q_175 : crapaud
q_176 : crocodile
q_177 : mercredi
q_178 : classe
q_179 : clou
q_180 : sac
q_181 : lac
q_182 : avec