In [25]:
import pandas as pd

In [26]:
df = pd.read_csv("questions_draft.txt" )

In [27]:
df

     question
0    Niveau A
1      Animal
2         Bol
3       Bille
4    Camarade
..        ...
141    Skieur
142  Souffrir
143    Soufre
144    Thorax
145  Tricycle

[146 rows x 1 columns]

In [28]:
df['key']=df.index

In [29]:
df

     question  key
0    Niveau A    0
1      Animal    1
2         Bol    2
3       Bille    3
4    Camarade    4
..        ...  ...
141    Skieur  141
142  Souffrir  142
143    Soufre  143
144    Thorax  144
145  Tricycle  145

[146 rows x 2 columns]

In [30]:
df['key']="q_"+df.key.astype(str)
dico = df.to_dict('records')

In [31]:
lista=[d['key']+" : " +d['question'] for d in dico]

In [32]:
for i in lista:
    print(i)

q_0 : Niveau A
q_1 : Animal
q_2 : Bol
q_3 : Bille
q_4 : Camarade
q_5 : Canal
q_6 : Caramel
q_7 : Carnaval
q_8 : Carton
q_9 : Chaleur
q_10 : Chose
q_11 : Farine
q_12 : Feu
q_13 : Fille
q_14 : Fleur
q_15 : Fromage
q_16 : Marche
q_17 : Neveu
q_18 : Noir
q_19 : Parent
q_20 : Partir
q_21 : Potiron
q_22 : Poulet
q_23 : Premier
q_24 : Sardine
q_25 : Seul
q_26 : Sucre
q_27 : Tartine
q_28 : Tasse
q_29 : Tigre
q_30 : Trou
q_31 : Vendredi
q_32 : Ventre
q_33 : Vitrine
q_34 : jambon
q_35 : Niveau B
q_36 : Acier
q_37 : Besoin
q_38 : Blouse
q_39 : Bois
q_40 : Campeur
q_41 : Chaise
q_42 : Chance
q_43 : Chanson
q_44 : Chienne
q_45 : Cousin
q_46 : Deux
q_47 : Dindon
q_48 : Espoir
q_49 : Fleuve
q_50 : Froid
q_51 : Gant
q_52 : Lange
q_53 : Ligne
q_54 : Long
q_55 : Montagne
q_56 : Orange
q_57 : Pantalon
q_58 : Poison
q_59 : Poisson
q_60 : Quille
q_61 : Raisin
q_62 : Renard
q_63 : Six
q_64 : Soigner
q_65 : Valise
q_66 : Volaille
q_67 : Voyage
q_68 : Niveau C
q_69 : Adresse
q_70 : Allonger
q_71 : Aviation
q_72 : Bijou
q_73 : Bouillon
q_74 : Caillou
q_75 : Carotte
q_76 : Champion
q_77 : Choix
q_78 : Commode
q_79 : Courrier
q_80 : Cravate
q_81 : Crayon
q_82 : Culotte
q_83 : Femme
q_84 : Feuille
q_85 : Fils
q_86 : Flamme
q_87 : Heureux
q_88 : Exciter
q_89 : Homme
q_90 : Horloger
q_91 : Jaloux
q_92 : Jamais
q_93 : Loup
q_94 : Monsieur
q_95 : Mouiller
q_96 : Oreiller
q_97 : Souhait
q_98 : Soupir
q_99 : Sourire
q_100 : Taquiner
q_101 : Terrain
q_102 : Toujours
q_103 : Tronc
q_104 : Pavillon
q_105 : Pigeon
q_106 : Pompon
q_107 : Examen
q_108 : Niveau D
q_109 : Accident
q_110 : Addition
q_111 : Agrafe
q_112 : Arracher
q_113 : Atterrir
q_114 : Autocar
q_115 : Buffet
q_116 : Ceinture
q_117 : Chahuter
q_118 : Clown
q_119 : Commis
q_120 : Comptoir
q_121 : Courir
q_122 : Cyclisme
q_123 : Dizaine
q_124 : Doigt
q_125 : Drap
q_126 : Dynamo
q_127 : Wagon
q_128 : Exclu
q_129 : Hache
q_130 : Hachis
q_131 : Hareng
q_132 : Houille
q_133 : Inclus
q_134 : Larynx
q_135 : Mourir
q_136 : Passion
q_137 : Photo
q_138 : Phrase
q_139 : Physique
q_140 : Plomb
q_141 : Skieur
q_142 : Souffrir
q_143 : Soufre
q_144 : Thorax
q_145 : Tricycle